In [157]:
import pandas as pd
df = pd.read_csv("New_Appartements.csv")

df.head()

,Type,Price,Location,Area,Pieces,Rooms,Bathrooms,Condition,Air conditioning,Garden,...,Concierge,Reinforced Door,Microwave,Fridge,TV,Washing machine,Sea views,Stage,Age,uknown
0,apartment,"3,500 TND",La Marsa inLa Marsa,180m²,4 Pieces,3 Rooms,3 Bathrooms,Good condition,yes,no,...,yes,no,no,no,no,no,yes,NaN,NaN,NaN
1,apartment,"2,500 TND",Yasmine Hammamet inHammamet,160m²,3 Pieces,2 Rooms,2 Bathrooms,New,yes,yes,...,yes,no,no,no,no,no,no,NaN,NaN,NaN
2,apartment,"1,500 TND",Hammamet Nord inHammamet,100m²,3 Pieces,2 Rooms,2 Bathrooms,New,yes,no,...,no,no,no,no,no,no,no,NaN,NaN,NaN
3,house,"5,000 TND",La Marsa inLa Marsa,800m²,6 Pieces,5 Rooms,3 Bathrooms,Good condition,yes,yes,...,no,no,no,no,no,no,no,NaN,NaN,NaN
4,house,"6,000 TND",La Marsa inLa Marsa,250m²,NaN,5 Rooms,NaN,NaN,no,no,...,no,no,no,no,no,no,no,NaN,NaN,NaN

In [158]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5565 entries, 0 to 5564
Data columns (total 34 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Type              5565 non-null   object
 1   Price             5049 non-null   object
 2   Location          5362 non-null   object
 3   Area              4592 non-null   object
 4   Pieces            4639 non-null   object
 5   Rooms             5299 non-null   object
 6   Bathrooms         5162 non-null   object
 7   Condition         5080 non-null   object
 8   Air conditioning  5322 non-null   object
 9   Garden            5322 non-null   object
 10  Heating           5322 non-null   object
 11  Furnished         5322 non-null   object
 12  Equipped kitchen  5322 non-null   object
 13  Double glazing    5322 non-null   object
 14  Security system   5322 non-null   object
 15  Terrace           5322 non-null   object
 16  Elevator          5322 non-null   object
 17  Satellite dish    5322 non-null   object
 18  Oven              5322 non-null   object
 19  Mountains views   5322 non-null   object
 20  Internet          5322 non-null   object
 21  Flooring          5322 non-null   object
 22  Garage            5322 non-null   object
 23  Pool              5322 non-null   object
 24  Concierge         5322 non-null   object
 25  Reinforced Door   5322 non-null   object
 26  Microwave         5322 non-null   object
 27  Fridge            5322 non-null   object
 28  TV                5322 non-null   object
 29  Washing machine   5322 non-null   object
 30  Sea views         5322 non-null   object
 31  Stage             1394 non-null   object
 32  Age               2359 non-null   object
 33  uknown            338 non-null    object
dtypes: object(34)
memory usage: 1.4+ MB

In [159]:
df.drop_duplicates(inplace=True)

df.drop(columns="Pieces", inplace=True)
df.drop(columns="Age", inplace=True)
df.drop(columns="uknown", inplace=True)
df.drop(columns="Stage", inplace=True)
df.head(20)

,Type,Price,Location,Area,Rooms,Bathrooms,Condition,Air conditioning,Garden,Heating,...,Flooring,Garage,Pool,Concierge,Reinforced Door,Microwave,Fridge,TV,Washing machine,Sea views
0,apartment,"3,500 TND",La Marsa inLa Marsa,180m²,3 Rooms,3 Bathrooms,Good condition,yes,no,yes,...,no,yes,no,yes,no,no,no,no,no,yes
1,apartment,"2,500 TND",Yasmine Hammamet inHammamet,160m²,2 Rooms,2 Bathrooms,New,yes,yes,yes,...,no,no,yes,yes,no,no,no,no,no,no
2,apartment,"1,500 TND",Hammamet Nord inHammamet,100m²,2 Rooms,2 Bathrooms,New,yes,no,yes,...,no,no,no,no,no,no,no,no,no,no
3,house,"5,000 TND",La Marsa inLa Marsa,800m²,5 Rooms,3 Bathrooms,Good condition,yes,yes,yes,...,no,yes,no,no,no,no,no,no,no,no
4,house,"6,000 TND",La Marsa inLa Marsa,250m²,5 Rooms,NaN,NaN,no,no,no,...,no,yes,yes,no,no,no,no,no,no,no
5,house,"6,500 TND",La Marsa inLa Marsa,480m²,3 Rooms,NaN,NaN,no,no,no,...,no,yes,yes,no,no,no,no,no,no,no
6,house,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,house,"6,000 TND",El Menzah 7 inAriana Ville,800m²,9 Rooms,4 Bathrooms,Good condition,yes,yes,yes,...,no,yes,no,no,no,no,no,no,no,no
17,apartment,"1,400 TND",Cité Ennasr 2 inAriana Ville,120m²,2 Rooms,2 Bathrooms,New,yes,no,yes,...,no,no,no,no,no,no,no,no,no,no
18,apartment,750 TND,Cité Ennkhilet inRaoued,95m²,2 Rooms,1 Bathroom,Good condition,no,no,yes,...,no,no,no,no,no,no,no,no,no,no
19,apartment,"1,100 TND",Sahloul inSousse Ville,120m²,2 Rooms,1 Bathroom,New,yes,no,yes,...,no,no,no,yes,no,no,no,no,no,no
20,house,"10,000 TND",Hammamet inHammamet,10000m²,5 Rooms,5 Bathrooms,Good condition,yes,yes,yes,...,no,no,yes,no,yes,yes,yes,yes,yes,no
21,house,"6,000 TND",Chott Meriem inAkouda,1000m²,7 Rooms,7 Bathrooms,Good condition,yes,yes,yes,...,no,yes,yes,no,yes,yes,yes,yes,yes,yes
22,house,"3,500 TND",Sidi Daoued inLa Marsa,150m²,4 Rooms,2 Bathrooms,Good condition,yes,yes,yes,...,no,yes,no,yes,no,no,no,no,no,no
23,house,"4,000 TND",Les Berges Du Lac 2 inLa Marsa,250m²,3 Rooms,2 Bathrooms,Good condition,yes,yes,yes,...,no,no,no,no,no,yes,no,no,no,no
24,apartment,"3,500 TND",La Marsa inLa Marsa,200m²,2 Rooms,1 Bathroom,Good condition,yes,no,yes,...,no,no,no,yes,yes,yes,yes,no,no,no
25,house,"1,200 TND",La Marsa inLa Marsa,130m²,2 Rooms,1 Bathroom,New,yes,no,no,...,no,no,no,no,no,no,no,no,no,no
26,apartment,"1,450 TND",Les Jardins de Carthage inLe Kram,90m²,2 Rooms,1 Bathroom,Good condition,yes,no,yes,...,no,no,no,yes,yes,yes,no,no,no,no
27,apartment,"4,300 TND",Les Berges Du Lac 1 inLa Marsa,190m²,3 Rooms,3 Bathrooms,New,yes,no,yes,...,no,yes,no,yes,yes,yes,no,no,no,yes
28,house,"3,600 TND",La Soukra inLa Soukra,400m²,3 Rooms,1 Bathroom,New,no,no,no,...,no,no,yes,no,no,no,no,no,no,no

In [160]:
df["Location"] = df["Location"].str.replace("inLa Marsa","")
df["Location"] = df["Location"].str.replace("inNabeul","")
df["Location"] = df["Location"].str.replace("inLe Kram","")
df["Location"] = df["Location"].str.replace("inHammamet","")
df["Location"] = df["Location"].str.replace("inCarthage","")
df["Location"] = df["Location"].str.replace("inAriana Ville","")
df["Location"] = df["Location"].str.replace("inSousse Ville","")
df["Location"] = df["Location"].str.replace("inLa Soukra","")
df["Location"] = df["Location"].str.replace("inSousse Jaouhara","")
df["Location"] = df["Location"].str.replace("inLe Bardo","")
df["Location"] = df["Location"].str.replace("inHammam Sousse","")
df["Location"] = df["Location"].str.replace("inLa Manouba","")
df["Location"] = df["Location"].str.replace("inEl Menzah","")
df["Location"] = df["Location"].str.replace("inCité El Khadra","")
df["Location"] = df["Location"].str.replace("inAkouda","")
df["Location"] = df["Location"].str.replace("inRaoued","")
df["Location"] = df["Location"].str.strip()

In [161]:
df["Price"] = df["Price"].str.replace("TND","")
df["Price"] = df["Price"].str.replace("EUR","")
df["Price"] = df["Price"].str.replace("Decreased by200","")
df["Price"] = df["Price"].str.replace("Decreased by500 ","")
df["Price"] = df["Price"].str.replace("Decreased by50","")
df["Price"] = df["Price"].str.replace("Decreased by90","")
df["Price"] = df["Price"].str.replace("Decreased by300","")
df["Price"] = df["Price"].str.replace("Decreased by100","")
df["Price"] = df["Price"].str.replace("Decreased by250","")
df["Price"] = df["Price"].str.replace("Decreased by150","")
df["Price"] = df["Price"].str.replace("Decreased by170","")
df["Price"] = df["Price"].str.replace("Decreased by30","")
df["Price"] = df["Price"].str.replace("Decreased by600","")
df["Price"] = df["Price"].str.replace("Decreased by400","")
df["Price"] = df["Price"].str.replace(",","")
df["Price"] = df["Price"].str.strip()

In [162]:
df["Rooms"] = df["Rooms"].str.replace("Rooms","")
df["Rooms"] = df["Rooms"].str.replace("Room","")
df["Rooms"] = df["Rooms"].str.strip()

In [163]:
df["Area"] = df["Area"].str.replace("m²","")
df["Area"] = df["Area"].str.strip()

In [164]:
df["Bathrooms"] = df["Bathrooms"].str.replace("Bathrooms","")
df["Bathrooms"] = df["Bathrooms"].str.replace("Bathroom","")
df["Bathrooms"] = df["Bathrooms"].str.strip()

In [165]:
df['Condition'].fillna(method='ffill', inplace=True) 
FeaturesToBeComplete = ['Sea views', 'Washing machine', 'TV', 'Mountains views', 'Reinforced Door',
                        'Air conditioning', 'Garden', 'Heating', 'Fridge', 'Microwave', 'Concierge',
                        'Pool', 'Garage', 'Flooring', 'Internet', 'Oven', 'Elevator', 'Satellite dish',
                        'Terrace', 'Security system', 'Double glazing', 'Equipped kitchen', 'Furnished']

for feature in FeaturesToBeComplete:
    if df[feature].isnull().all:
        df[feature] = df[feature].fillna("no")

df = df.drop(6)

C:\Users\MSI\AppData\Local\Temp\ipykernel_10720\3435931574.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Condition'].fillna(method='ffill', inplace=True)

In [166]:
df["Price"] = df["Price"].str.replace(" ","")
df = df.dropna(subset=['Price'])
df.head(30)

,Type,Price,Location,Area,Rooms,Bathrooms,Condition,Air conditioning,Garden,Heating,...,Flooring,Garage,Pool,Concierge,Reinforced Door,Microwave,Fridge,TV,Washing machine,Sea views
0,apartment,3500,La Marsa,180,3,3,Good condition,yes,no,yes,...,no,yes,no,yes,no,no,no,no,no,yes
1,apartment,2500,Yasmine Hammamet,160,2,2,New,yes,yes,yes,...,no,no,yes,yes,no,no,no,no,no,no
2,apartment,1500,Hammamet Nord,100,2,2,New,yes,no,yes,...,no,no,no,no,no,no,no,no,no,no
3,house,5000,La Marsa,800,5,3,Good condition,yes,yes,yes,...,no,yes,no,no,no,no,no,no,no,no
4,house,6000,La Marsa,250,5,NaN,Good condition,no,no,no,...,no,yes,yes,no,no,no,no,no,no,no
5,house,6500,La Marsa,480,3,NaN,Good condition,no,no,no,...,no,yes,yes,no,no,no,no,no,no,no
16,house,6000,El Menzah 7,800,9,4,Good condition,yes,yes,yes,...,no,yes,no,no,no,no,no,no,no,no
17,apartment,1400,Cité Ennasr 2,120,2,2,New,yes,no,yes,...,no,no,no,no,no,no,no,no,no,no
18,apartment,750,Cité Ennkhilet,95,2,1,Good condition,no,no,yes,...,no,no,no,no,no,no,no,no,no,no
19,apartment,1100,Sahloul,120,2,1,New,yes,no,yes,...,no,no,no,yes,no,no,no,no,no,no
20,house,10000,Hammamet,10000,5,5,Good condition,yes,yes,yes,...,no,no,yes,no,yes,yes,yes,yes,yes,no
21,house,6000,Chott Meriem,1000,7,7,Good condition,yes,yes,yes,...,no,yes,yes,no,yes,yes,yes,yes,yes,yes
22,house,3500,Sidi Daoued,150,4,2,Good condition,yes,yes,yes,...,no,yes,no,yes,no,no,no,no,no,no
23,house,4000,Les Berges Du Lac 2,250,3,2,Good condition,yes,yes,yes,...,no,no,no,no,no,yes,no,no,no,no
24,apartment,3500,La Marsa,200,2,1,Good condition,yes,no,yes,...,no,no,no,yes,yes,yes,yes,no,no,no
25,house,1200,La Marsa,130,2,1,New,yes,no,no,...,no,no,no,no,no,no,no,no,no,no
26,apartment,1450,Les Jardins de Carthage,90,2,1,Good condition,yes,no,yes,...,no,no,no,yes,yes,yes,no,no,no,no
27,apartment,4300,Les Berges Du Lac 1,190,3,3,New,yes,no,yes,...,no,yes,no,yes,yes,yes,no,no,no,yes
28,house,3600,La Soukra,400,3,1,New,no,no,no,...,no,no,yes,no,no,no,no,no,no,no
29,apartment,3800,Les Berges Du Lac 2,190,3,1,New,yes,no,no,...,no,no,no,no,no,no,yes,no,no,no
30,apartment,5500,Les Berges Du Lac 2,300,3,1,New,yes,no,yes,...,no,no,yes,no,yes,yes,yes,no,no,no
31,apartment,4300,Les Berges Du Lac 1,180,3,3,New,yes,no,yes,...,no,yes,no,yes,yes,yes,yes,yes,yes,no
44,apartment,2500,La Marsa,94,1,1,New,yes,no,no,...,no,no,no,no,no,no,no,no,no,no
45,apartment,2700,Gammarth,200,2,1,New,yes,yes,yes,...,no,no,no,no,yes,no,yes,no,yes,no
47,house,2850,Hammamet,442,4,3,New,yes,yes,yes,...,no,yes,yes,yes,no,no,yes,yes,yes,yes
49,apartment,2500,Gammarth,NaN,2,2,Good condition,yes,yes,yes,...,no,no,no,no,no,yes,yes,yes,yes,no
50,apartment,4500,Les Berges Du Lac 2,180,3,2,New,yes,no,no,...,no,no,no,no,no,no,no,no,no,no
51,apartment,12500,Les Berges Du Lac 2,753,5,5,Good condition,yes,yes,yes,...,no,yes,yes,no,yes,yes,yes,no,yes,no
52,apartment,2500,Les Berges Du Lac 2,130,2,2,Good condition,yes,no,yes,...,no,yes,no,yes,yes,yes,yes,yes,yes,no
53,apartment,1200,La Marsa,130,2,1,New,yes,no,no,...,no,no,no,no,no,no,no,no,no,no

In [167]:
df.shape

(5031, 30)

In [168]:
df.to_csv("cleaned_dataset.csv", index=False)