In [127]:
import pandas as pd
import numpy as np


df = pd.read_csv("cleaned_dataset.csv")
df.head()

,Type,Price,Location,Area,Rooms,Bathrooms,Condition,Air conditioning,Garden,Heating,...,Flooring,Garage,Pool,Concierge,Reinforced Door,Microwave,Fridge,TV,Washing machine,Sea views
0,apartment,3500,La Marsa,180.0,3.0,3.0,Good condition,yes,no,yes,...,no,yes,no,yes,no,no,no,no,no,yes
1,apartment,2500,Yasmine Hammamet,160.0,2.0,2.0,New,yes,yes,yes,...,no,no,yes,yes,no,no,no,no,no,no
2,apartment,1500,Hammamet Nord,100.0,2.0,2.0,New,yes,no,yes,...,no,no,no,no,no,no,no,no,no,no
3,house,5000,La Marsa,800.0,5.0,3.0,Good condition,yes,yes,yes,...,no,yes,no,no,no,no,no,no,no,no
4,house,6000,La Marsa,250.0,5.0,NaN,Good condition,no,no,no,...,no,yes,yes,no,no,no,no,no,no,no

In [128]:
df = df.dropna(subset=['Price'])
df = df.dropna(subset=['Area'])
df = df.dropna(subset=['Rooms'])
df = df.dropna(subset=['Bathrooms'])

In [129]:
df["Price"] = df["Price"].str.replace("Decreasedby1000","")
df["Price"] = df["Price"].str.replace("Decreasedby3000","")
df["Price"] = df["Price"].str.replace("Decreasedby1000","")
df["Price"] = df["Price"].str.replace("Decreasedby1500","")
df["Price"] = df["Price"].str.replace("Decreasedby800","")
df["Price"] = df["Price"].str.replace("Decreasedby700","")
df["Price"] = df["Price"].str.replace("Decreasedby40","")

In [130]:
df['Price'] = df['Price'].astype(float)
df['Area'] = df['Area'].astype(int)
df['Rooms'] = df['Rooms'].astype(int)
df['Bathrooms'] = df['Bathrooms'].astype(int)
df[df['Price'] > 20000]

,Type,Price,Location,Area,Rooms,Bathrooms,Condition,Air conditioning,Garden,Heating,...,Flooring,Garage,Pool,Concierge,Reinforced Door,Microwave,Fridge,TV,Washing machine,Sea views
412,house,1500000.0,La Manouba,666,9,3,Good condition,yes,yes,yes,...,no,yes,no,no,no,no,no,no,no,no
496,apartment,550000.0,Les Jardins de Carthage,110,2,2,New,yes,yes,yes,...,no,yes,yes,yes,yes,yes,yes,no,no,no
594,apartment,600000.0,La Marsa,176,2,2,Good condition,yes,yes,yes,...,no,no,no,yes,yes,no,yes,no,no,no
772,apartment,72000.0,Bouficha,62,2,1,Good condition,no,no,no,...,no,no,no,no,no,no,no,no,no,no
948,house,24000.0,Les Berges Du Lac 2,1200,5,5,Good condition,yes,yes,yes,...,no,yes,yes,yes,yes,no,no,no,no,yes
1027,apartment,300000.0,Hammam Sousse,100,2,2,New,yes,no,yes,...,no,no,no,no,no,yes,yes,yes,yes,no
1117,apartment,675000.0,Les Jardins de Carthage,150,3,2,Good condition,yes,no,yes,...,no,yes,no,yes,yes,yes,yes,no,no,no
1158,house,24000.0,Les Berges Du Lac 2,1500,5,7,Good condition,yes,yes,yes,...,no,yes,yes,no,yes,yes,yes,no,yes,no
1223,house,7000000.0,Mutuelle Ville,500,6,6,Good condition,yes,yes,yes,...,no,yes,yes,no,no,no,no,no,no,no
1228,apartment,700000.0,Ain Zaghouan Nord,150,2,1,Good condition,no,no,no,...,no,no,no,no,no,no,no,no,no,no
1331,apartment,790000.0,La Soukra,210,3,3,Good condition,yes,no,yes,...,no,yes,no,yes,yes,yes,no,no,yes,no
1691,apartment,148000.0,Bab Bhar inTunis,50,1,1,Good condition,no,no,no,...,no,no,no,no,no,no,no,no,no,no
1804,house,24000.0,Les Berges Du Lac 2,1300,9,5,Good condition,yes,yes,yes,...,no,yes,yes,no,yes,yes,yes,no,no,no
2529,apartment,450000.0,Hammamet,72,2,1,Good condition,no,no,no,...,no,no,no,no,no,no,no,no,no,no
2711,apartment,550000.0,El Kantaoui,150,3,2,New,yes,no,yes,...,no,no,no,no,no,no,no,no,no,no
3047,house,720000.0,Sidi Mansour inSfax Ville,2200,7,3,New,yes,yes,yes,...,no,yes,no,no,yes,yes,yes,yes,yes,no
3467,apartment,230000.0,Aouina,78,1,1,Good condition,yes,no,yes,...,no,no,no,yes,no,no,no,no,no,no
3629,apartment,335000.0,Aouina,161,3,2,Good condition,no,no,yes,...,no,no,no,no,no,no,no,no,no,no
3790,apartment,255000.0,Hammamet Nord,65,1,1,Good condition,no,no,yes,...,no,no,no,no,yes,no,no,no,no,no
3901,house,879000.0,Chotrana 1,250,4,3,New,yes,yes,yes,...,no,yes,no,yes,yes,yes,no,no,no,no
4055,house,450000.0,Houmt Souk inHoumt Souk,463,3,2,Good condition,no,yes,no,...,no,yes,no,no,no,no,no,no,no,no
4120,house,260000.0,Sousse Riadh inSousse Riadh,370,3,1,Good condition,no,no,no,...,no,yes,no,no,no,no,no,no,no,no
4186,apartment,2000000.0,Mutuelle Ville,557,6,4,Good condition,no,yes,no,...,no,yes,no,no,no,no,no,no,no,no
4220,apartment,299000.0,Yasmine Hammamet,130,2,2,Good condition,no,no,no,...,no,no,no,no,no,no,no,no,no,no
4296,apartment,2300000.0,Carthage,200,3,2,New,yes,no,yes,...,no,no,no,no,no,no,no,no,no,no
4301,house,3000000.0,Sidi Bousaid,556,4,3,Good condition,yes,yes,yes,...,no,yes,no,no,yes,no,no,no,no,no
4379,apartment,70000.0,La Marsa,4000,6,2,Good condition,no,no,no,...,no,yes,no,no,no,no,no,no,no,no
4550,apartment,111111.0,CitÃ© El Wafa,75,1,1,New,yes,yes,yes,...,no,yes,yes,yes,no,no,yes,yes,yes,yes
4628,house,400000.0,La Soukra,165,4,3,Good condition,yes,no,yes,...,no,yes,no,no,no,no,no,no,no,no
4814,house,30000.0,Sidi Bousaid,1200,8,10,New,no,no,no,...,no,no,yes,no,no,no,no,no,no,no
4988,apartment,250000.0,Les Berges Du Lac 1,64,1,1,Good condition,no,no,no,...,no,yes,no,no,no,no,no,no,no,no

In [131]:
df = df[df['Price'] <= 10000]
df = df[df['Area'] <= 5000]


df = df[(df['Type'] != 'apartment') | ((df['Type'] == 'apartment') & (df['Area'] <= 5000))]


df.shape

(4061, 30)

In [132]:
df.to_csv("cleaned_dataset.csv", index=False)

In [133]:
df.head()

,Type,Price,Location,Area,Rooms,Bathrooms,Condition,Air conditioning,Garden,Heating,...,Flooring,Garage,Pool,Concierge,Reinforced Door,Microwave,Fridge,TV,Washing machine,Sea views
0,apartment,3500.0,La Marsa,180,3,3,Good condition,yes,no,yes,...,no,yes,no,yes,no,no,no,no,no,yes
1,apartment,2500.0,Yasmine Hammamet,160,2,2,New,yes,yes,yes,...,no,no,yes,yes,no,no,no,no,no,no
2,apartment,1500.0,Hammamet Nord,100,2,2,New,yes,no,yes,...,no,no,no,no,no,no,no,no,no,no
3,house,5000.0,La Marsa,800,5,3,Good condition,yes,yes,yes,...,no,yes,no,no,no,no,no,no,no,no
6,house,6000.0,El Menzah 7,800,9,4,Good condition,yes,yes,yes,...,no,yes,no,no,no,no,no,no,no,no